package com.example.emergency.agent.tools

import android.content.Context
import com.example.emergency.agent.Tool
import com.example.emergency.agent.ToolResult
import com.example.emergency.agent.tools.rag.RagBootstrap
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

/**
 * Medical RAG tool. Hybrid (MiniLM embeddings + BM25, RRF-fused) retrieval
 * over a prebuilt chunk index. The retriever is warmed up at app start by
 * [RagBootstrap]; this tool just consumes it.
 *
 * Index lives in assets/rag/ and is generated by
 *   data-pipeline/build_rag_index.py
 */
class MedicalRagTool(@Suppress("UNUSED_PARAMETER") context: Context) {

    fun getTool(): Tool = Tool(
        name = "search_medical_database",
        description = "Retrieves authoritative medical protocols for specific procedures or treatments (e.g. 'tourniquet application', 'burn care', 'CPR', 'choking', 'anaphylaxis'). Required param: query. Call this when you need protocol-level detail you don't already have. DO NOT call for: image descriptions (use vision), yes/no judgment questions, follow-ups already covered by a prior result, or definitional/conversational turns.",
        execute = ::execute,
    )

    private suspend fun execute(params: Map<String, String>): ToolResult {
        val query = params["query"]?.trim().orEmpty()
        if (query.isEmpty()) {
            return ToolResult(success = false, data = "", error = "No query provided")
        }

        // RagBootstrap.get() blocks if warm-up is still running. Stay off
        // the main thread.
        val r = withContext(Dispatchers.IO) { RagBootstrap.get() }
            ?: return ToolResult(
                success = false,
                data = "",
                error = "Medical RAG index not loaded: ${RagBootstrap.failureMessage() ?: "unknown"}",
            )

        val hits = withContext(Dispatchers.Default) { r.retrieve(query, k = 4) }
        if (hits.isEmpty()) {
            return ToolResult(success = true, data = "No relevant medical information found for: $query")
        }

        // Collapse hits from the same source doc so the LLM sees a coherent
        // protocol rather than three near-duplicate snippets.
        val grouped = hits.groupBy { it.chunk.docTitle }

        val text = buildString {
            appendLine("Medical database results for '$query':\n")
            grouped.entries.take(3).forEachIndexed { i, (title, chunks) ->
                val cat = chunks.first().chunk.category
                appendLine("${i + 1}. $title ($cat)")
                chunks.distinctBy { it.chunk.section }.take(2).forEach { rc ->
                    if (rc.chunk.section.isNotBlank()) appendLine("[${rc.chunk.section}]")
                    appendLine(rc.chunk.text)
                }
                appendLine()
            }
        }.trim()

        return ToolResult(success = true, data = text)
    }
}
