#!/usr/bin/env python3
"""Regenerate the public catalog.json from a directory of built region tarballs.

The catalog file the app reads (per plan §6) lists every available pack
with its download URL, sha256, byte size, name, type, ISO and bbox. After
the GitHub Actions workflow finishes building tarballs, this script:

  1. Loads scripts/build-pack/regions.json (the source of truth).
  2. Walks the tarball directory, picking up every <id>-v<n>.tar.gz that
     was actually produced (the workflow may skip large/marked entries).
  3. Reads sha256 + size from disk for each.
  4. Combines region metadata + tarball facts into the catalog.
  5. Writes catalog.json (default to stdout, --output to write a file).

URLs are templated: --url-base "https://github.com/<owner>/<repo>/releases/download/<tag>"
yields "<base>/<id>-v<n>.tar.gz" per entry.

Usage from the workflow:
    python3 scripts/build-pack/regenerate-catalog.py \
        --tarball-dir dist/ \
        --url-base "https://github.com/${{ github.repository }}/releases/download/packs-latest" \
        --output app/src/main/assets/bundled/catalog.json

Usage locally to test:
    python3 scripts/build-pack/regenerate-catalog.py \
        --tarball-dir scripts/build-pack/dist/ \
        --url-base "file:///tmp/packs"
"""
from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import os
import re
import sys
from pathlib import Path

CATALOG_SCHEMA_VERSION = 1
TARBALL_RE = re.compile(r"^(?P<id>[a-z0-9-]+)-v(?P<version>\d+)\.tar\.gz$")
CHUNK = 1024 * 1024  # 1 MB stream buffer


def sha256_of(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        while True:
            buf = fh.read(CHUNK)
            if not buf:
                break
            h.update(buf)
    return h.hexdigest()


def load_regions(regions_path: Path) -> dict[str, dict]:
    """Return { id: region_entry } for every entry in regions.json."""
    catalog = json.loads(regions_path.read_text())
    out: dict[str, dict] = {}
    for entry in catalog.get("regions", []):
        if not isinstance(entry, dict):
            continue
        rid = entry.get("id")
        if rid:
            out[rid] = entry
    return out


def discover_tarballs(tarball_dir: Path) -> list[tuple[str, int, Path]]:
    """Return [(id, version, path), ...] - one entry per region id, picking
    the highest version found. Older versions stay in the release as a
    rollback safety net but never appear in the catalog (the app would
    otherwise show "Netherlands" twice in the picker).
    """
    by_id: dict[str, tuple[int, Path]] = {}
    if not tarball_dir.is_dir():
        return []
    for entry in sorted(tarball_dir.iterdir()):
        m = TARBALL_RE.match(entry.name)
        if not m:
            continue
        rid = m.group("id")
        version = int(m.group("version"))
        existing = by_id.get(rid)
        if existing is None or version > existing[0]:
            by_id[rid] = (version, entry)
    return [(rid, v, p) for rid, (v, p) in sorted(by_id.items())]


def build_catalog(
    regions: dict[str, dict],
    tarballs: list[tuple[str, int, Path]],
    url_base: str,
) -> dict:
    """Combine region metadata + tarball facts into the catalog payload."""
    packs: list[dict] = []
    for rid, version, path in tarballs:
        meta = regions.get(rid)
        if meta is None:
            print(f"  WARN: tarball {path.name} has no entry in regions.json — skipping", file=sys.stderr)
            continue
        size_bytes = path.stat().st_size
        sha = sha256_of(path)
        pack: dict = {
            "id": rid,
            "name": meta.get("name", rid),
            "type": meta.get("type", "country"),
            "bbox": meta["bbox"],
            "sizeBytes": size_bytes,
            "version": version,
            "url": f"{url_base.rstrip('/')}/{path.name}",
            "sha256": sha,
        }
        if iso := meta.get("iso"):
            pack["iso"] = iso
        if country := meta.get("country"):
            pack["country"] = country
        packs.append(pack)

    return {
        "schemaVersion": CATALOG_SCHEMA_VERSION,
        "lastUpdated": dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "_comment": (
            "Auto-generated by scripts/build-pack/regenerate-catalog.py from "
            "the tarballs in dist/. Do not edit by hand — your changes will be "
            "overwritten on the next workflow run."
        ),
        "packs": packs,
    }


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--regions",
        type=Path,
        default=Path(__file__).parent / "regions.json",
        help="Path to regions.json (default: alongside this script).",
    )
    parser.add_argument(
        "--tarball-dir",
        type=Path,
        required=True,
        help="Directory holding <id>-v<n>.tar.gz files.",
    )
    parser.add_argument(
        "--url-base",
        required=True,
        help="URL prefix the app will fetch from. Filenames are appended.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        help="Output path for catalog.json. If omitted, writes to stdout.",
    )
    args = parser.parse_args(argv)

    regions = load_regions(args.regions)
    print(f"Loaded {len(regions)} regions from {args.regions}", file=sys.stderr)

    tarballs = discover_tarballs(args.tarball_dir)
    print(f"Found {len(tarballs)} tarballs in {args.tarball_dir}", file=sys.stderr)

    catalog = build_catalog(regions, tarballs, args.url_base)
    serialised = json.dumps(catalog, indent=2)

    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(serialised + "\n")
        print(f"Wrote {len(catalog['packs'])} pack entries to {args.output}", file=sys.stderr)
    else:
        sys.stdout.write(serialised + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
